### ISSUE TITLE
Reserved time renamed to Planned in Slurm 23.02

### ISSUE THREAD

**Issue by lgorenstein** [birc-aeh/slurm-utils#12]
We've just upgraded Slurm to 23.02 on one of our clusters, and `jobinfo` suddenly stopped working with `sacct: error: Invalid field requested: "reserved"`

Turns out, `Reserved` time is now called `Planned` in `sacct` (as of [23.02.0rc1](https://github.com/SchedMD/slurm/blob/974fe335c6881786280a3b5813c935a1e09ed523/NEWS#LL326C1-L327C40)):
```
 -- sacct - Rename 'Reserved' field to 'Planned' to match sreport and the
    nomenclature of the 'Planned' node.
```

**Comment by lgorenstein** [comment]
Not quite sure how to best incorporate this into `jobinfo`.  In a pinch, a quick 
```
 def f_time(x, meta):
-    all_times = [meta.timelimit, meta.elapsed, meta.TotalCPU, meta.reserved]
+    all_times = [meta.timelimit, meta.elapsed, meta.TotalCPU, meta.planned]
```
has bandaided it for us for now.  But iIdeally this would be auto-determined based on Slurm version (which I see has been recently introduced into `jobinfo` 🎉).  Looks like you'd also need checking for _Max_ Slurm version (not just _Min_ one)?

Or am I overcomplicating and something like
```
 all_times = [meta.timelimit, meta.elapsed, meta.TotalCPU, 
              meta.reserved if slurm.version < ("23", "02") else meta.planned]
```
could do?

**Comment by birc-aeh** [comment]
Can you try if this was fixed with the latest commit?

**Comment by lgorenstein** [comment]
Thank you, confirming it to work like a charm on both old[er] and new Slurm.

A quick bug report: looks like both 'planned' and 'reserved' dictionary entries have "letter O" (not "zero") in their minor versions:
```
field_minimum_version = {
   "planned": ("23", "O2"),
}

field_maximum_version = {
    "reserved": ("22", "O5"),
}
```

**Comment by birc-aeh** [comment]
Great!
My normal 0 button is broken on this keyboard and it seems numpad 0 has a weird interaction with ssh+vim 😆
