### ISSUE TITLE
Some more about interpreters

### ISSUE THREAD

**Issue by lgorenstein** [birc-aeh/slurm-utils#13]
`jobinfo` uses the usual `#!/usr/bin/env python` shebang line for portability.  However, some Linux distros (CentOS 8 and Rocky 8 of the ones I know) have chosen not to include a `python` executable (i.e. there are explicit `/usr/bin/python2` and `/usr/bin/python3`, but not a `/usr/bin/python`). 

Given Python 2 deprecation, perhaps worth changing the interpreter line to be `#!/usr/bin/env python3`?

**Comment by birc-aeh** [comment]
They are not even guaranteed to have those unfortunately. All we have on our centos8 test machines is `/usr/libexec/platform-python`.

I've changed the default to python3 now and added a note to the readme.
