### ISSUE TITLE
A "Waited" field?

### ISSUE THREAD

**Issue by lgorenstein** [birc-aeh/slurm-utils#4]
Hi Anders,

A thought: people often like to know how long their job has waited in the queue before it started execution (and oftentimes this is par of agreed upon QoS, etc).  Can a nicely formatted  `Waited:` field (a.k.a. `Start - Submit`) be added to jobinfo output, as most humans are not good at subtracting date-times in their heads?

**Comment by birc-aeh** [comment]
Sure, I will take a look at it tomorrow or Wednesday.

**Comment by birc-aeh** [comment]
Turns out there already is a field for this in `sacct`. It doesn't measure from the submission time though, but from the eligible time. So if the job is waiting for its dependencies to finish the `Waited` time won't increase.

Is this sufficient or do you think there should also be time since submission?

**Comment by lgorenstein** [comment]
That's probably fair. The tool we have here for PBS does a naive `Started - Submitted` count, but you are right, this number is not quite a QoS metric. I think measuring from eligibility should work.

**Comment by lgorenstein** [comment]
Also, I would probably make it to fall back to an actual numeric `0` rather than `--` if the job started immediately :)

**Comment by birc-aeh** [comment]
Should print now, even if 00:00:00.

Maybe I should have a `--json` or `--parsable` flag and try to make the default output more human readable. I don't know if anyone is parsing the current output :)

**Comment by lgorenstein** [comment]
--parsable (and --parsable2 :) sound like a good enhancement.

My current plan is to utilize the tool in mostly human-facing scenarios, but ability to do machine parsing definitely is (or at least could be) useful.
