### ISSUE TITLE
More user-friendly install info

### ISSUE THREAD

**Issue by tomMoral** [birc-aeh/slurm-utils#6]
Hi all,

Thanks for this very useful tool!

One thing that would be nice would be to improve the installation process as it is not so clear what is the recommended way of installing this.

For now, if I understood correctly, the method is to clone the repo and then add the two command tools to the `PATH`. Putting some instruction on how to do so would be nice.

In the future, do you plan to package this tool in `pypi` with a `setup.py` so users can simply install this with `pip install slurm-utils`?

**Comment by birc-aeh** [comment]
Hi Tom

Yes, the idea has always been for the scripts to be self contained so you can just download them to your PATH.

I have added some installation instructions but I don't think a `pypi` package is in the cards :)

**Comment by tomMoral** [comment]
Nice for the instruction, I think it can help new users familiarize more easily with the tools.

If you are interested in packaging this with `pip` installable package, I can give it a go in a PR. If not, I also get it.

**Comment by birc-aeh** [comment]
Thanks, but creating the package isn't really my concern. I just don't want to make sure the package stays up to date or have to explain the difference between `pip install` and `pip install --user`, interaction with virtualenv/conda environments etc.

It makes more sense to me as a sort of "statically linked executable" that you install globally for your user or for the entire system.

**Comment by tomMoral** [comment]
Alright! thanks for the explanation and for updating the readme.
