### ISSUE TITLE
Error executing gnodes

### ISSUE THREAD

**Issue by raivivek** [birc-aeh/slurm-utils#7]
Hi, when executing `gnodes` on an HPC I have access to, I get the following error:
```
Traceback (most recent call last):
  File "./gnodes", line 354, in <module>
    main(args.partitions, set(args.groups), set(args.accounts), pattern)
  File "./gnodes", line 287, in main
    node_job_meta[n].job_ids.add(jobid)
KeyError: 'falcon'
```

`falcon` is the name of the node; and looks like the error stems from the lack of response from `get_line('Partitions', line)`. I checked the output of `NODE_CMD` command and it doesn't contain any Partition information. It could also be possible that my input here is premature so let me know what else I can provide.

**Comment by birc-aeh** [comment]
Can you check what version you are running (`sinfo --version`) and see if there is any output about partitions in this command: `scontrol show node -a --oneliner | head | grep Partitions`

**Comment by raivivek** [comment]
```
$ sinfo --version
slurm 16.05.9
```

For the latter command, I get no output.

**Comment by birc-aeh** [comment]
I guess the minimum version has crept up over the years :disappointed: 
I only have access to our own cluster for testing, so you will have to grab an older version of the script unfortunately.

**Comment by raivivek** [comment]
No worries. I'll try to modify and open a PR if successfully done in a back-compatible way. Otherwise, for now you can note this caveat somewhere in README. This issue is resolved as far as I'm concerned. Thanks!
