### ISSUE TITLE
Update to python 3

### ISSUE THREAD

**Issue by duboism** [birc-aeh/slurm-utils#9]
Hi,

We want to install `slurm-utils` on our new cluster which will soon drop python 2 (which reached its EOL in 2020). It would be great to upgrade to python 3.

According to our tests, using `2to3` is enough. With a few hacks, it should not be hard to have something working on python 2 and python 3.

I can try to open a PR for that.

Thanks in advance,
Mathieu

**Comment by duboism** [comment]
See #11.

**Comment by birc-aeh** [comment]
Thanks!

**Comment by duboism** [comment]
Thanks ! Let's hope I haven't goofed.
